<!-- Skid Steering Drive -->
<robot name="robot_controller" xmlns:xacro="http://wiki.ros.org/xacro">
  <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>100.0</updateRate>
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>true</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
      <rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
      <leftRearJoint>left_back_wheel_joint</leftRearJoint>
      <rightRearJoint>right_back_wheel_joint</rightRearJoint>
      <wheelSeparation>${wheel_joint_y*2}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <torque>100</torque>
      <topicName>cmd_vel</topicName>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame>
      <broadcastTF>1</broadcastTF>

    </plugin>
  </gazebo>
</robot>
 