<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_lidar">

  <!-- Lidar property -->
  <xacro:property name="laser_m" value="0.1" /> <!-- 雷达质量 -->
  <xacro:property name="laser_length" value="0.07" /> <!-- 雷达长度 -->
  <xacro:property name="laser_radius" value="0.04" /> <!-- 雷达半径 -->
  <xacro:property name="laser_x" value="0.0" /> <!-- 雷达安装的x坐标 -->
  <xacro:property name="laser_y" value="0.0" /> <!-- 雷达安装的y坐标 -->
  <xacro:property name="laser_z" value="${tank_body_length / 2 + laser_length / 2}" /> <!-- 雷达安装的z坐标:支架高度 / 2 + 雷达高度 / 2  -->

  <link name="laser">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_length}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_length}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial_matrix m="${laser_m}" r="${laser_radius}" h="${laser_length}" />
  </link>

  <joint name="laser_joint" type="fixed">
    <origin xyz="${laser_x} ${laser_y} ${laser_z}" rpy="0.0 0.0 0.0" />
    <parent link="tank_body" />
    <child link="laser" />
  </joint>

  <gazebo reference="laser">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- 配置雷达传感器信息 -->
  <gazebo reference="laser">
    <sensor type="ray" name="rplidar">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>5.5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3</min_angle>
            <max_angle>3</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_rplidar" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>laser</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>