<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- PROPERTY LIST -->
  <xacro:property name="M_PI" value="3.1415926" />
  <xacro:property name="base_footprint_radius" value="0.001" />

  <xacro:property name="base_length" value="0.8" />
  <xacro:property name="base_width" value="0.5" />
  <xacro:property name="base_height" value="0.12" />
  <xacro:property name="base_mass" value="1" />


  <xacro:property name="wheel_mass" value="0.2" />
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_length" value="0.04" />
  <xacro:property name="wheel_joint_x" value="${base_length/2*0.6}" />
  <xacro:property name="wheel_joint_y" value="${base_width/2}" />
  <xacro:property name="wheel_joint_z" value="-${base_height/2}" />

  <xacro:property name="tank_body_mass" value="1" />
  <xacro:property name="tank_body_radius" value="0.17" />
  <xacro:property name="tank_body_length" value="0.3" />

  <xacro:property name="cannon_radius" value="0.05" />
  <xacro:property name="cannon_length" value="0.7" />
  <xacro:property name="cannon_mass" value="0.7" />
  <xacro:property name="cannon_offset_x" value="0.5" />
 

  <!-- Defining the colors used in this robot -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0" />
  </material>
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0" />
  </material>
  <material name="green">
    <color rgba="0.0 1.0 0.0 1.0" />
  </material>
  <material name="grey">
    <color rgba="0.2 0.2 0.2 1.0" />
  </material>
  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0" />
  </material>
  <material name="brown">
    <color rgba="${205/255} ${127/255} ${50/255} 1.0" />
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0" />
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0" />
  </material>
  <material name="silver">
    <color rgba="0.75 0.75 0.75 1" />
  </material>

  <link name="base_footprint">
    <visual name="base_footprint">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <sphere radius="${base_footprint_radius}" />
      </geometry>
    </visual>
  </link>
  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0.0 0.0 ${base_height*0.8}" rpy="0.0 0.0 0.0" />
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
    <xacro:Box_inertial_matrix m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}" />
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Macro for robot wheel -->
  <xacro:macro name="wheels" params="prefix reflect1 reflect2">
    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="${reflect1*wheel_joint_x} ${reflect2*wheel_joint_y} ${wheel_joint_z}" rpy="0.0 0.0 0.0" />
      <parent link="base_link" />
      <child link="${prefix}_wheel_link" />
      <axis xyz="0.0 1.0 0.0" />
    </joint>

    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="${M_PI/2} 0.0 0.0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="${M_PI/2} 0.0 0.0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
      </collision>
      <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>

  </xacro:macro>

  <xacro:wheels prefix="left_front" reflect1="1" reflect2="1" />
  <xacro:wheels prefix="left_back" reflect1="-1" reflect2="1" />
  <xacro:wheels prefix="right_front" reflect1="1" reflect2="-1" />
  <xacro:wheels prefix="right_back" reflect1="-1" reflect2="-1" />

  <!-- tank_body -->
  <link name="tank_body">
    <visual>
      <origin xyz=" 0 0 0.0" rpy=" 0 0 0" />
      <geometry>
        <cylinder radius="${tank_body_radius}" length="${tank_body_length}" />
      </geometry>
      <material name="orange" />
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${tank_body_radius}" length="${tank_body_length}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial_matrix m="${tank_body_mass}" r="${tank_body_radius}" h="${tank_body_length}" />
  </link>

  <joint name=" body_base_joint" type="fixed">
    <origin xyz=" 0.0 0.0 ${base_height/2+tank_body_length/2}" rpy=" 0.0 0.0 0.0" />
    <parent link="base_link" />
    <child link="tank_body" />
  </joint>

  <gazebo reference="tank_body">
    <material>Gazebo/Orange</material>
  </gazebo>


  <!-- cannon -->
  <joint name="canon_body_joint" type="fixed">
    <origin xyz="${cannon_offset_x} 0.0 0.0" rpy=" 0.0 ${M_PI/2} 0.0" />
    <parent link="tank_body" />
    <child link="cannon" />
  </joint>

  <link name="cannon">
    <visual>
      <origin xyz="0 0 0" rpy=" 0 0 0" />
      <geometry>
        <cylinder radius="${cannon_radius}" length="${cannon_length}" />
      </geometry>
      <material name="silver" />
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${cannon_radius}" length="${cannon_length}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial_matrix m="${cannon_mass}" r="${cannon_radius}" h="${cannon_length}" />
  </link>

  <gazebo reference="cannon">
    <material>Gazebo/Silver</material>
  </gazebo>


</robot> 