<?xml version="1.0"?>
<robot name="camera" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- camere property -->
  <xacro:property name="camera_length" value="0.05" /> <!-- 摄像头长度(x) -->
  <xacro:property name="camera_width" value="0.07" /> <!-- 摄像头宽度(y) -->
  <xacro:property name="camera_height" value="0.02" /> <!-- 摄像头高度(z) -->
  <xacro:property name="camera_x" value="0.17" /> <!-- 摄像头安装的x坐标 -->
  <xacro:property name="camera_y" value="0.0" /> <!-- 摄像头安装的y坐标 -->
  <xacro:property name="camera_z" value="${tank_body_length/2 + camera_height/2 - 0.05}" />
  <xacro:property name="camera_mass" value="0.01" /> <!-- 摄像头质量 -->

  <link name="camera">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}" />
      </geometry>
    </collision>
    <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}" />
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="${camera_x} ${camera_y} ${camera_z}" rpy="0 0.0 0.0" />
    <parent link="tank_body" />
    <child link="camera" />
  </joint>

  <gazebo reference="camera">
    <material>Gazebo/Black</material>
  </gazebo>


  <!-- 配置摄像头传感器信息 -->
  <gazebo reference="camera">
    <!-- 类型设置为 camara -->
    <sensor type="camera" name="camera_node">
      <update_rate>30.0</update_rate> <!-- 更新频率 -->
      <!-- 摄像头基本信息设置 -->
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>1280</width>
          <height>720</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <!-- 核心插件 -->
      <plugin name="gazebo_camera" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>/camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>

</robot>




 